export enum AppRoutes {
  Auth = 'auth',
  EquipMent = 'equipment',
  Equipments = 'equipments',
  Users = 'users',
  Admin = 'admin',
  Management = 'management',
  Profile = 'profile',
  Catalog = 'catalog',
  Categories = 'categories',
  EquipmentRegistration = 'equipment-registration',
  PublicOffer = 'public-offer',
  Forbidden = 'forbidden',
  Roles = 'roles',
  EmailConfirmation = 'email-confirmation',
}
