export type Equipment = {
  category: string;
  compensationCost: number;
  condition: string;
  description: string;
  inventoryNumber: number;
  id: number;
  kind: number;
  location: number;
  maximumAmount: number;
  maximumDays: number;
  name: string;
  name_substring: string;
  order: number;
  photo: string;
  receiptDate: string;
  status: number;
  supplier: string;
  title: string;
};
