import {
  MainHeaderComponent,
  InfoModalComponent,
  FakeInputComponent,
  ConfirmationModalComponent,
  CatalogFilterComponent,
  BlockUiComponent,
  PageNotFoundComponent,
  NotificationComponent,
  PersonalInfoModalComponent,
  PublicOfferComponent,
  TableComponent,
  MainNavComponent,
  ModalLayoutComponent,
  PageForbiddenComponent,
} from '../components';
import { CatalogSearchComponent } from '@shared/components/catalog-search/catalog-search.component';

export const sharedComponents = [
  BlockUiComponent,
  MainHeaderComponent,
  PageNotFoundComponent,
  NotificationComponent,
  PersonalInfoModalComponent,
  PublicOfferComponent,
  ConfirmationModalComponent,
  FakeInputComponent,
  PageForbiddenComponent,
  InfoModalComponent,
  TableComponent,
  MainNavComponent,
  ModalLayoutComponent,
  CatalogFilterComponent,
  CatalogSearchComponent,
];
