import {
  BlockUiComponent,
  CatalogFilterComponent,
  ConfirmationModalComponent,
  ErrorPageLayoutComponent,
  FakeInputComponent,
  InfoModalComponent,
  MainHeaderComponent,
  MainNavComponent,
  ModalLayoutComponent,
  NotificationComponent,
  PageForbiddenComponent,
  PageNotFoundComponent,
  PersonalInfoModalComponent,
  PublicOfferComponent,
  TableComponent,
  CatalogSearchComponent,
  TableFilterComponent,
  ChangeEmailModalComponent,
  UserDetailsComponent,
} from '../components';

export const sharedComponents = [
  BlockUiComponent,
  MainHeaderComponent,
  PageNotFoundComponent,
  NotificationComponent,
  PublicOfferComponent,
  ConfirmationModalComponent,
  FakeInputComponent,
  PageForbiddenComponent,
  InfoModalComponent,
  TableComponent,
  MainNavComponent,
  ModalLayoutComponent,
  CatalogFilterComponent,
  CatalogSearchComponent,
  ErrorPageLayoutComponent,
  TableFilterComponent,
  PersonalInfoModalComponent,
  ChangeEmailModalComponent,
  UserDetailsComponent,
];
